-- Code generated by protoc-gen-saber-seaql. DO NOT EDIT.
-- versions:
--   - protoc-gen-saber-seaql {{.Version}}
--   - protoc             {{.ProtocVersion}}
{{- if .IsDeprecated}}
-- {{.Source}} is a deprecated file.
{{- else}}
-- source: {{.Source}}
{{- end}}
-- 
-- {{.Table.Comment}}
CREATE TABLE 
	`{{.Table.Name}}` (
	{{- $colen := len .Table.Columns}}
	{{- $idxlen := len .Table.Indexes}}
	{{- range $idx, $e := .Table.Columns}}
		`{{$e.Name}}` {{$e.Type}} COMMENT '{{$e.Comment}}'{{- if eq (add $colen -1) $idx}}{{- if gt $idxlen 0}},{{- end}}{{- else}},{{- end}}
	{{- end}}
	{{- range $idx, $e := .Table.Indexes}}
		{{$e}}{{- if ne (add $idxlen -1)  $idx}},{{- end}}
	{{- end}}
	) ENGINE = {{.Table.Engine}} DEFAULT CHARSET = {{.Table.Charset}} COLLATE = {{.Table.Collate}} COMMENT = '{{.Table.Comment}}';