-- Code generated by protoc-gen-saber-seaql. DO NOT EDIT.
-- versions:
--   - protoc-gen-saber-seaql {{.Version}}
--   - protoc             {{.ProtocVersion}}
{{- if .IsDeprecated}}
-- {{.Source}} is a deprecated file.
{{- else}}
-- source: {{.Source}}
{{- end}}
-- 
-- {{.Table.Comment}}
{{- $colen := len .Table.Columns}}
{{- $idxlen := len .Table.Indexes}}
CREATE TABLE 
	`{{.Table.Name}}` (
	{{- $colen = add $colen -1}}
	{{- $idxlen = add $idxlen -1}}
	{{- range $idx, $e := .Table.Columns}}
		`{{$e.Name}}` {{$e.Type}} COMMENT '{{$e.Comment}}'{{- if eq $colen $idx }}{{- if gt $idxlen 0}},{{- end}}{{- else}},{{- end}}
	{{- end}}
	{{- range $idx, $e := .Table.Indexes}}
		{{$e}}{{- if ne $idxlen  $idx}},{{- end}}
	{{- end}}
	) ENGINE = {{.Table.Engine}} DEFAULT CHARSET = {{.Table.Charset}} COLLATE = {{.Table.Collate}} COMMENT = '{{.Table.Comment}}';