// Code generated by protoc-gen-saber-enum. DO NOT EDIT.
// versions:
//   - protoc-gen-saber-enum {{.Version}}
//   - protoc             {{.ProtocVersion}}
{{- if .IsDeprecated}}
// {{.Source}} is a deprecated file.
{{- else}}
// source: {{.Source}}
{{- end}}

package {{.Package}}

{{- range $e := .Enums}}
// __{{- if $e.MessageName}}{{$e.MessageName}}_{{- end}}{{$e.Name}}Mapping {{$e.Name}} mapping
var __{{- if $e.MessageName}}{{$e.MessageName}}_{{- end}}{{$e.Name}}Mapping = map[{{- if $e.MessageName}}{{$e.MessageName}}_{{- end}}{{$e.Name}}]string{
{{- range $ee := $e.Values}}
	{{$ee.Number}}: "{{$ee.Mapping}}",
{{- end}}
}
// Get{{- if $e.MessageName}}{{$e.MessageName}}_{{- end}}{{$e.Name}}Desc get mapping description
// {{$e.Comment}}
func Get{{- if $e.MessageName}}{{$e.MessageName}}_{{- end}}{{$e.Name}}Desc(t {{if $e.MessageName}}{{$e.MessageName}}_{{end}}{{$e.Name}}) string {
	return __{{- if $e.MessageName}}{{$e.MessageName}}_{{- end}}{{$e.Name}}Mapping[t]
}
{{- end}}

