// Code generated by protoc-gen-saber-enum. DO NOT EDIT.
// versions:
//   - protoc-gen-saber-enum {{.Version}}
//   - protoc             {{.ProtocVersion}}
{{- if .IsDeprecated}}
// {{.Source}} is a deprecated file.
{{- else}}
// source: {{.Source}}
{{- end}}

package {{.Package}}

func EnumComment() []map[int32]string {
	return []map[int32]string{
{{- range $e := .Enums}}
	{
	{{- range $ee := $e.Values}}
		int32({{- if $e.MessageName}}{{$e.MessageName}}{{- else}}{{$e.Name}}{{- end}}_{{$ee.Value}}): "{{$ee.Mapping}}",
	{{- end}}
	},
{{- end}}
	}
}