// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.2
// source: nested.proto

package enums

import (
	_ "github.com/things-go/protogen-saber/protosaber/enumerate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status 状态值
type Nested_Status int32

const (
	// 未定义
	Nested_STATUS_UNSPECIFIED Nested_Status = 0
	// 打开
	Nested_STATUS_UP Nested_Status = 1
	// 关闭
	Nested_STATUS_DOWN Nested_Status = 2
	// 左
	Nested_STATUS_LEFT Nested_Status = 3
	// 右
	Nested_STATUS_RIGHT Nested_Status = 4
)

// Enum value maps for Nested_Status.
var (
	Nested_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_UP",
		2: "STATUS_DOWN",
		3: "STATUS_LEFT",
		4: "STATUS_RIGHT",
	}
	Nested_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_UP":          1,
		"STATUS_DOWN":        2,
		"STATUS_LEFT":        3,
		"STATUS_RIGHT":       4,
	}
)

func (x Nested_Status) Enum() *Nested_Status {
	p := new(Nested_Status)
	*p = x
	return p
}

func (x Nested_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Nested_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_nested_proto_enumTypes[0].Descriptor()
}

func (Nested_Status) Type() protoreflect.EnumType {
	return &file_nested_proto_enumTypes[0]
}

func (x Nested_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Nested_Status.Descriptor instead.
func (Nested_Status) EnumDescriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{0, 0}
}

type Nested_Nested1_Type int32

const (
	// 未定义
	Nested_Nested1_TYPE_DISABLE Nested_Nested1_Type = 0
	// 打开
	Nested_Nested1_TYPE_Enable Nested_Nested1_Type = 1
)

// Enum value maps for Nested_Nested1_Type.
var (
	Nested_Nested1_Type_name = map[int32]string{
		0: "TYPE_DISABLE",
		1: "TYPE_Enable",
	}
	Nested_Nested1_Type_value = map[string]int32{
		"TYPE_DISABLE": 0,
		"TYPE_Enable":  1,
	}
)

func (x Nested_Nested1_Type) Enum() *Nested_Nested1_Type {
	p := new(Nested_Nested1_Type)
	*p = x
	return p
}

func (x Nested_Nested1_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Nested_Nested1_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_nested_proto_enumTypes[1].Descriptor()
}

func (Nested_Nested1_Type) Type() protoreflect.EnumType {
	return &file_nested_proto_enumTypes[1]
}

func (x Nested_Nested1_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Nested_Nested1_Type.Descriptor instead.
func (Nested_Nested1_Type) EnumDescriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Nested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nested) Reset() {
	*x = Nested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nested_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{0}
}

type Nested_Nested1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nested_Nested1) Reset() {
	*x = Nested_Nested1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nested_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nested_Nested1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested_Nested1) ProtoMessage() {}

func (x *Nested_Nested1) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested_Nested1.ProtoReflect.Descriptor instead.
func (*Nested_Nested1) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{0, 0}
}

var File_nested_proto protoreflect.FileDescriptor

var file_nested_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x5f, 0x73, 0x61, 0x62, 0x65, 0x72, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x1a, 0x19, 0x65,
	0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x02, 0x0a, 0x06, 0x4e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x1a, 0x4f, 0x0a, 0x07, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x31, 0x22, 0x44,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44,
	0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x00, 0x1a, 0x09, 0x9a, 0x3f, 0x06, 0xe7, 0xa6, 0x81,
	0xe7, 0x94, 0xa8, 0x12, 0x1a, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x10, 0x01, 0x1a, 0x09, 0x9a, 0x3f, 0x06, 0xe5, 0x90, 0xaf, 0xe7, 0x94, 0xa8, 0x1a,
	0x03, 0x90, 0x3f, 0x01, 0x22, 0xa6, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x24, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x1a, 0x0c, 0x9a, 0x3f, 0x09, 0xe6, 0x9c, 0xaa, 0xe5,
	0xae, 0x9a, 0xe4, 0xb9, 0x89, 0x12, 0x19, 0x0a, 0x09, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x50, 0x10, 0x01, 0x1a, 0x0a, 0x9a, 0x3f, 0x07, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x31,
	0x12, 0x1b, 0x0a, 0x0b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10,
	0x02, 0x1a, 0x0a, 0x9a, 0x3f, 0x07, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x32, 0x12, 0x1b, 0x0a,
	0x0b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x03, 0x1a, 0x0a,
	0x9a, 0x3f, 0x07, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x33, 0x12, 0x1c, 0x0a, 0x0c, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x04, 0x1a, 0x0a, 0x9a, 0x3f,
	0x07, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x34, 0x1a, 0x03, 0x90, 0x3f, 0x01, 0x42, 0x50, 0x0a,
	0x1a, 0x63, 0x6e, 0x2e, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x2d, 0x67, 0x6f, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x42, 0x05, 0x45, 0x6e, 0x75,
	0x6d, 0x73, 0x50, 0x01, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x3b, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nested_proto_rawDescOnce sync.Once
	file_nested_proto_rawDescData = file_nested_proto_rawDesc
)

func file_nested_proto_rawDescGZIP() []byte {
	file_nested_proto_rawDescOnce.Do(func() {
		file_nested_proto_rawDescData = protoimpl.X.CompressGZIP(file_nested_proto_rawDescData)
	})
	return file_nested_proto_rawDescData
}

var file_nested_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nested_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nested_proto_goTypes = []interface{}{
	(Nested_Status)(0),       // 0: protogen_saber.examples.enums.Nested.Status
	(Nested_Nested1_Type)(0), // 1: protogen_saber.examples.enums.Nested.Nested1.Type
	(*Nested)(nil),           // 2: protogen_saber.examples.enums.Nested
	(*Nested_Nested1)(nil),   // 3: protogen_saber.examples.enums.Nested.Nested1
}
var file_nested_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nested_proto_init() }
func file_nested_proto_init() {
	if File_nested_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nested_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nested_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nested_Nested1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nested_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nested_proto_goTypes,
		DependencyIndexes: file_nested_proto_depIdxs,
		EnumInfos:         file_nested_proto_enumTypes,
		MessageInfos:      file_nested_proto_msgTypes,
	}.Build()
	File_nested_proto = out.File
	file_nested_proto_rawDesc = nil
	file_nested_proto_goTypes = nil
	file_nested_proto_depIdxs = nil
}
