// Code generated by protoc-gen-saber-enum. DO NOT EDIT.
// versions:
//   - protoc-gen-saber-enum v0.0.3
//   - protoc             v4.22.2
// source: nested.proto

package enums

// Enum value mapping for Nested_Status.
var (
	__Nested_StatusMapping_Desc = map[Nested_Status]string{
		0:   "\"unspecified\", aaaa",
		1:   "nested1",
		2:   "nested2",
		3:   "nested3",
		4:   "nested4",
		999: "end",
	}
	__Nested_StatusMapping_Value = map[string]Nested_Status{
		"\"unspecified\", aaaa": 0,
		"nested1":               1,
		"nested2":               2,
		"nested3":               3,
		"nested4":               4,
		"end":                   999,
	}
)

// GetNested_StatusDesc get mapping description
// Status 状态值, [0:\"unspecified\", aaaa,1:nested1,2:nested2,3:nested3,4:nested4,999:end]
func GetNested_StatusDesc(t Nested_Status) string {
	return __Nested_StatusMapping_Desc[t]
}

// GetNested_StatusValue get mapping value
// Status 状态值, [0:\"unspecified\", aaaa,1:nested1,2:nested2,3:nested3,4:nested4,999:end]
func GetNested_StatusValue(s string) int {
	return int(__Nested_StatusMapping_Value[s])
}

// Enum value mapping for Nested_Nested1_Type.
var (
	__Nested_Nested1_TypeMapping_Desc = map[Nested_Nested1_Type]string{
		0: "禁用",
		1: "启用",
	}
	__Nested_Nested1_TypeMapping_Value = map[string]Nested_Nested1_Type{
		"禁用": 0,
		"启用": 1,
	}
)

// GetNested_Nested1_TypeDesc get mapping description
// Type 类型, [0:禁用,1:启用]
func GetNested_Nested1_TypeDesc(t Nested_Nested1_Type) string {
	return __Nested_Nested1_TypeMapping_Desc[t]
}

// GetNested_Nested1_TypeValue get mapping value
// Type 类型, [0:禁用,1:启用]
func GetNested_Nested1_TypeValue(s string) int {
	return int(__Nested_Nested1_TypeMapping_Value[s])
}
