// Code generated by protoc-gen-saber-enum. DO NOT EDIT.
// versions:
//   - protoc-gen-saber-enum v0.0.6
//   - protoc             v4.24.0
// source: nested.proto

package enums

import (
	"strconv"
)

// Enum value mapping for Nested_Status.
var (
	__Nested_StatusMapping_Desc = map[Nested_Status]string{
		0:   "\"unspecified\", aaaa",
		1:   "nested1",
		2:   "nested2",
		3:   "nested3",
		4:   "nested4",
		999: "end",
	}
	__Nested_StatusMapping_Value = map[string]Nested_Status{
		"\"unspecified\", aaaa": 0,
		"nested1":               1,
		"nested2":               2,
		"nested3":               3,
		"nested4":               4,
		"end":                   999,
	}
)

// IntoNumber returns the enum value as an integer.
func (x Nested_Status) IntoNumber() int32 {
	return int32(x)
}

// IntoNumberString returns the enum value as an integer string.
func (x Nested_Status) IntoNumberString() string {
	return strconv.FormatInt(int64(x), 10)
}

// MappingDescriptor mapping description.
// Status 状态值, [0:\"unspecified\", aaaa,1:nested1,2:nested2,3:nested3,4:nested4,999:end]
func (x Nested_Status) MappingDescriptor() string {
	return __Nested_StatusMapping_Desc[x]
}

// EnumCount the number of enum values.
func (Nested_Status) EnumCount() int {
	return 6
}

// Value_Status_Unspecified \"unspecified\", aaaa
func (Nested_Status) Value_Unspecified() Nested_Status {
	return Nested_Status_Unspecified
}

// Value_Status_Up nested1
func (Nested_Status) Value_Up() Nested_Status {
	return Nested_Status_Up
}

// Value_Status_Down nested2
func (Nested_Status) Value_Down() Nested_Status {
	return Nested_Status_Down
}

// Value_Status_Left nested3
func (Nested_Status) Value_Left() Nested_Status {
	return Nested_Status_Left
}

// Value_Status_Right nested4
func (Nested_Status) Value_Right() Nested_Status {
	return Nested_Status_Right
}

// Value_Status_End end
func (Nested_Status) Value_End() Nested_Status {
	return Nested_Status_End
}

// GetNested_StatusValue get mapping value
// Status 状态值, [0:\"unspecified\", aaaa,1:nested1,2:nested2,3:nested3,4:nested4,999:end]
func GetNested_StatusValue(s string) int {
	return int(__Nested_StatusMapping_Value[s])
}

// Enum value mapping for Nested_Nested1_Type.
var (
	__Nested_Nested1_TypeMapping_Desc = map[Nested_Nested1_Type]string{
		0: "禁用",
		1: "启用",
	}
	__Nested_Nested1_TypeMapping_Value = map[string]Nested_Nested1_Type{
		"禁用": 0,
		"启用": 1,
	}
)

// IntoNumber returns the enum value as an integer.
func (x Nested_Nested1_Type) IntoNumber() int32 {
	return int32(x)
}

// IntoNumberString returns the enum value as an integer string.
func (x Nested_Nested1_Type) IntoNumberString() string {
	return strconv.FormatInt(int64(x), 10)
}

// MappingDescriptor mapping description.
// Type 类型, [0:禁用,1:启用]
func (x Nested_Nested1_Type) MappingDescriptor() string {
	return __Nested_Nested1_TypeMapping_Desc[x]
}

// EnumCount the number of enum values.
func (Nested_Nested1_Type) EnumCount() int {
	return 2
}

// Value_Type_Disable 禁用
func (Nested_Nested1_Type) Value_Disable() Nested_Nested1_Type {
	return Nested_Nested1_Type_Disable
}

// Value_Type_Enable 启用
func (Nested_Nested1_Type) Value_Enable() Nested_Nested1_Type {
	return Nested_Nested1_Type_Enable
}

// GetNested_Nested1_TypeValue get mapping value
// Type 类型, [0:禁用,1:启用]
func GetNested_Nested1_TypeValue(s string) int {
	return int(__Nested_Nested1_TypeMapping_Value[s])
}
