// Code generated by protoc-gen-saber-enum. DO NOT EDIT.
// versions:
//   - protoc-gen-saber-enum v0.0.3
//   - protoc             v4.22.2
// source: non_nested.proto

package enums

// Enum value mapping for NonNestedStatus.
var (
	__NonNestedStatusMapping_Desc = map[NonNestedStatus]string{
		0: "未定义",
		1: "打开",
		2: "关闭",
		3: "左",
		4: "右",
	}
	__NonNestedStatusMapping_Value = map[string]NonNestedStatus{
		"未定义": 0,
		"打开":  1,
		"关闭":  2,
		"左":   3,
		"右":   4,
	}
)

// GetNonNestedStatusDesc get mapping description
// Foo 状态值, [0:未定义,1:打开,2:关闭,3:左,4:右]
func GetNonNestedStatusDesc(t NonNestedStatus) string {
	return __NonNestedStatusMapping_Desc[t]
}

// GetNonNestedStatusValue get mapping value
// Foo 状态值, [0:未定义,1:打开,2:关闭,3:左,4:右]
func GetNonNestedStatusValue(s string) int {
	return int(__NonNestedStatusMapping_Value[s])
}
