// Code generated by protoc-gen-saber-enum. DO NOT EDIT.
// versions:
//   - protoc-gen-saber-enum v0.0.1
//   - protoc             v3.21.2
// source: non_nested.proto

package enums

// __NonNestedStatusMapping NonNestedStatus mapping
var __NonNestedStatusMapping = map[int]string{
	0: "未定义",
	1: "打开",
	2: "关闭",
	3: "左",
	4: "右",
}

// GetNonNestedStatusDesc get mapping description
//
//	Foo 状态值, [0:未定义,1:打开,2:关闭,3:左,4:右]
func GetNonNestedStatusDesc(t int) string {
	return __NonNestedStatusMapping[t]
}
