// Code generated by protoc-gen-saber-enum. DO NOT EDIT.
// versions:
//   - protoc-gen-saber-enum v0.0.6
//   - protoc             v4.24.0
// source: non_nested.proto

package enums

import (
	"strconv"
)

// Enum value mapping for NonNestedStatus.
var (
	__NonNestedStatusMapping_Desc = map[NonNestedStatus]string{
		0: "未定义",
		1: "打开",
		2: "关闭",
		3: "左",
		4: "右",
	}
	__NonNestedStatusMapping_Value = map[string]NonNestedStatus{
		"未定义": 0,
		"打开":  1,
		"关闭":  2,
		"左":   3,
		"右":   4,
	}
)

// IntoNumber returns the enum value as an integer.
func (x NonNestedStatus) IntoNumber() int32 {
	return int32(x)
}

// IntoNumberString returns the enum value as an integer string.
func (x NonNestedStatus) IntoNumberString() string {
	return strconv.FormatInt(int64(x), 10)
}

// MappingDescriptor mapping description.
// NonNestedStatus 状态值, [0:未定义,1:打开,2:关闭,3:左,4:右]
func (x NonNestedStatus) MappingDescriptor() string {
	return __NonNestedStatusMapping_Desc[x]
}

// EnumCount the number of enum values.
func (NonNestedStatus) EnumCount() int {
	return 5
}

// Value_NonNestedStatus_Unspecified 未定义
func (NonNestedStatus) Value_Unspecified() NonNestedStatus {
	return NonNestedStatus_NonNestedStatus_Unspecified
}

// Value_NonNestedStatus_Up 打开
func (NonNestedStatus) Value_Up() NonNestedStatus {
	return NonNestedStatus_NonNestedStatus_Up
}

// Value_NonNestedStatus_Down 关闭
func (NonNestedStatus) Value_Down() NonNestedStatus {
	return NonNestedStatus_NonNestedStatus_Down
}

// Value_NonNestedStatus_Left 左
func (NonNestedStatus) Value_Left() NonNestedStatus {
	return NonNestedStatus_NonNestedStatus_Left
}

// Value_NonNestedStatus_Right 右
func (NonNestedStatus) Value_Right() NonNestedStatus {
	return NonNestedStatus_NonNestedStatus_Right
}

// GetNonNestedStatusValue get mapping value
// NonNestedStatus 状态值, [0:未定义,1:打开,2:关闭,3:左,4:右]
func GetNonNestedStatusValue(s string) int {
	return int(__NonNestedStatusMapping_Value[s])
}
