-- Code generated by protoc-gen-saber-seaql. DO NOT EDIT.
-- versions:
--   - protoc-gen-saber-seaql v0.0.1
--   - protoc             v3.21.2
-- source: seaql.proto
-- 
-- Dict 字典表
CREATE TABLE 
	`dict` (
		`id` bigint NOT NULL AUTO_INCREMENT COMMENT '系统序号',
		`key` varchar(64) NOT NULL DEFAULT '' COMMENT '名称',
		`name` varchar(64) NOT NULL DEFAULT '' COMMENT '名称',
		`is_pin` tinyint(1) NOT NULL COMMENT COMMENT '是否锁定',
		`created_at` datetime NOT NULL COMMENT '创建时间',
		`updated_at` datetime NOT NULL COMMENT '更新时间',
		PRIMARY KEY (`id`),
		KEY `idx_key` (`key`) USING BTREE
	) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'Dict 字典表';