-- Code generated by protoc-gen-saber-seaql. DO NOT EDIT.
-- versions:
--   - protoc-gen-saber-seaql v0.1.0
--   - protoc                 v4.24.0
-- source: seaql.proto

-- 字典表
CREATE TABLE 
	`dict_annote` (
		`id` bigint NOT NULL AUTO_INCREMENT COMMENT '系统序号',
		`key` varchar(64) NOT NULL DEFAULT '' COMMENT '键',
		`name` varchar(64) NOT NULL DEFAULT '' COMMENT '名称',
		`is_pin` tinyint(1) NOT NULL COMMENT '是否锁定',
		`created_at` datetime NOT NULL COMMENT '创建时间',
		`updated_at` datetime NOT NULL COMMENT '更新时间',
		PRIMARY KEY (`id`),
		UNIQUE KEY `uk_key_value` (`key`, `value`) USING BTREE
	) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '字典表';
