-- Code generated by protoc-gen-saber-seaql. DO NOT EDIT.
-- versions:
--   - protoc-gen-saber-seaql v0.0.1
--   - protoc             v3.21.2
-- source: seaql.proto
-- 
-- DictItem 字典项表
CREATE TABLE 
	`dict_item` (
		`id` bigint NOT NULL AUTO_INCREMENT COMMENT '系统序号',
		`dict_id` bigint NOT NULL COMMENT '字典id',
		`key` varchar(64) NOT NULL DEFAULT '' COMMENT '关键字',
		`name` varchar(64) NOT NULL DEFAULT '' COMMENT '名称',
		`created_at` datetime NOT NULL COMMENT '创建时间',
		`updated_at` datetime NOT NULL COMMENT '更新时间'
	) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'DictItem 字典项表';